replicaCount: 1

imagePullSecrets:
  - name: docker-config-secret-frontend

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "128Mi"

fqdn: "<FQDN>"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "<FQDN>"
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - "<FQDN>"

service:
  type: ClusterIP
  port: 8080

configName: nginx-conf

configData:
  nginx.conf: |
    server {

      listen 80;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /momo-store/css/ {
            alias   /usr/share/nginx/html/css/;
            try_files $uri $uri/ =404;
          }

      location /momo-store/img/ {
        alias   /usr/share/nginx/html/img/;
        try_files $uri $uri/ =404;
      }

      location /momo-store/js/ {
        alias   /usr/share/nginx/html/js/;
        try_files $uri $uri/ =404;
      }
      
      location = /momo-store/favicon.ico {
        alias   /usr/share/nginx/html/favicon.ico;
        try_files $uri $uri/ =404;
      }

      error_page   500 502 503 504  /50x.html;
      
      location = /50x.html {
          root   /usr/share/nginx/html;
      } 

    }
