replicaCount: 1

imagePullSecrets:
  - name: docker-config-dumplings-frontend

rollingUpdateEnabled: true
rollingUpdate:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 50%

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "128Mi"

fqdn: "po-khmel.space"

hpa:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "po-khmel.space"
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - "po-khmel.space"

service:
  type: ClusterIP
  port: 80

configName: nginx-conf

configData:
  nginx.conf: |
    server {

      listen 80;

      location ~ ^/(products|categories|orders|auth/whoami|health|metrics) {
        proxy_pass http://backend:8081;
      }

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /css/ {
        alias   /usr/share/nginx/html/css/;
        try_files $uri $uri/ =404;
      }

      location /img/ {
        alias   /usr/share/nginx/html/img/;
        try_files $uri $uri/ =404;
      }

      location /js/ {
        alias   /usr/share/nginx/html/js/;
        try_files $uri $uri/ =404;
      }
      
      location = /favicon.ico {
        alias   /usr/share/nginx/html/favicon.ico;
        try_files $uri $uri/ =404;
      }

      error_page   500 502 503 504  /50x.html;
      
      location = /50x.html {
        root   /usr/share/nginx/html;
      } 
    }
