apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumplings-backend
  labels:
    app: dumplings-backend
spec:
  replicas: 2
  revisionHistoryLimit: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 50%
  selector:
    matchLabels:
      app: dumplings-backend
  template:
    metadata:
      labels:
        app: dumplings-backend
    spec:
      imagePullSecrets:
        - name: docker-config-dumplings-backend
      containers:
        - name: dumplings-backend
          image: gitlab.praktikum-services.ru:5050/std-017-042/dumplingstore/dumplings-backend:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - name: dumplings-backend
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
