apiVersion: v1
kind: Secret
metadata:
  name: docker-config-dumplings-backend
  labels:
    app: dumplings-backend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4Tnkwd05ESTZOemh4ZHpZM1JWRT0iCgkJfQoJfQp9
