apiVersion: v1
kind: Service
metadata:
  name: dumplings-backend-service
  labels:
    app: dumplings-backend
spec:
  type: ClusterIP
  selector:
    app: dumplings-backend
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
