apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dumplings-ingress
  labels:
    name: dumplings-ingress
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - <Host>
  rules:
    - host: <Host>
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: dumplings-frontend
                port:
                  number: 8080
