apiVersion: v1
kind: Service
metadata:
  name: dumplings-frontend-service
  labels:
    app: dumplings-frontend
spec:
  type: ClusterIP
  selector:
    app: dumplings-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
