---
- name: Install Docker on Ubuntu 20.04
  hosts: all
  become: true

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - gnupg
          - ca-certificates
          - curl
          - lsb-release
        state: present
      tags:
        - install

    - name: Create directory for Docker GPG file
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      tags:
        - setup

    - name: Download Docker GPG file
      ansible.builtin.get_url:
        url: '{{ docker_repo_url }}/gpg'
        dest: '{{ docker_gpg_path }}'
        mode: '0644'
      tags:
        - setup

    - name: Add Docker repository to sources.list.d
      ansible.builtin.apt_repository:
        repo: 'deb [arch={{ docker_arch }} signed-by={{ docker_gpg_path }}] {{ docker_repo_url }} {{ docker_codename }} stable'
        state: present
      tags:
        - setup

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      tags:
        - update

    - name: Install Docker-CE (Community Edition), the Docker-CE CLI, the containerd runtime, and Docker Compose
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      tags:
        - install

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
      tags:
        - install
