---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-dumplings-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.gitlabSecretData }}
