replicaCount: 2

podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "8081"
  prometheus.io/scrape: "true"

imagePullSecrets:
  - name: docker-config-dumplings-backend

resources:
  limits:
    memory: "1Gi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"

rollingUpdateEnabled: true
rollingUpdate:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 50%

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: "nginx"

fqdn: "po-khmel.space"
