---
- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: latest
    update_cache: true
  tags: install

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
  tags: install

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: setup

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  tags: setup

- name: Install Docker-CE (Community Edition), the Docker-CE CLI, the containerd runtime, and Docker Compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true
  tags: install

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  tags: install
